@php
    /** @var \App\Models\Tenancy $tenancy */
    $unit = $tenancy->unit;
    $property = $unit->property;
    $rm = fn ($v) => 'RM '.number_format((float) $v, 2);
@endphp
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Tenancy Agreement #{{ $tenancy->id }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111; line-height: 1.5; }
        h1 { font-size: 18px; text-align: center; margin: 0 0 4px; }
        .sub { text-align: center; color: #555; margin-bottom: 24px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
        td { padding: 6px 8px; border: 1px solid #ccc; vertical-align: top; }
        td.k { width: 35%; background: #f5f5f5; font-weight: bold; }
        h2 { font-size: 13px; margin: 18px 0 6px; }
        ol { padding-left: 18px; margin: 0; }
        .sign { margin-top: 48px; width: 100%; }
        .sign td { border: none; width: 50%; padding-top: 40px; }
        .line { border-top: 1px solid #111; padding-top: 4px; }
    </style>
</head>
<body>
    <h1>TENANCY AGREEMENT</h1>
    <div class="sub">Agreement No. TA-{{ str_pad((string) $tenancy->id, 5, '0', STR_PAD_LEFT) }} · Generated by SewaHub</div>

    <h2>1. Parties</h2>
    <table>
        <tr><td class="k">Landlord</td><td>{{ $property->owner->name }} ({{ $property->owner->email }})</td></tr>
        <tr><td class="k">Tenant</td><td>{{ $tenancy->tenant->name }} ({{ $tenancy->tenant->email }}, {{ $tenancy->tenant->phone }})</td></tr>
    </table>

    <h2>2. Premises</h2>
    <table>
        <tr><td class="k">Property</td><td>{{ $property->name }}</td></tr>
        <tr><td class="k">Unit</td><td>{{ $unit->code }} ({{ $unit->type->label() }})</td></tr>
        <tr><td class="k">Address</td><td>{{ $property->address }}, {{ $property->postcode }} {{ $property->city }}, {{ $property->state }}</td></tr>
    </table>

    <h2>3. Terms</h2>
    <table>
        <tr><td class="k">Start date</td><td>{{ $tenancy->start_date->format('d M Y') }}</td></tr>
        <tr><td class="k">End date</td><td>{{ $tenancy->end_date?->format('d M Y') ?? 'Month-to-month' }}</td></tr>
        <tr><td class="k">Monthly rent</td><td>{{ $rm($tenancy->monthly_rent) }}, due on day {{ $tenancy->due_day }} of each month</td></tr>
        <tr><td class="k">Security deposit</td><td>{{ $rm($tenancy->deposit_amount) }}</td></tr>
    </table>

    <h2>4. Conditions</h2>
    <ol>
        <li>Rent is payable on or before the due day each month. Late payment may incur a late fee.</li>
        <li>The deposit is refundable at the end of the tenancy, less any unpaid rent or damage.</li>
        <li>The tenant shall keep the premises clean and report repairs through SewaHub.</li>
        <li>Either party may end this tenancy with one (1) month written notice.</li>
    </ol>

    <table class="sign">
        <tr>
            <td><div class="line">Landlord: {{ $property->owner->name }}</div></td>
            <td><div class="line">Tenant: {{ $tenancy->tenant->name }}</div></td>
        </tr>
    </table>
</body>
</html>
